version: '3.8'

services:
  dev_db:
    container_name: dev_db
    image: postgres
    environment:
      - POSTGRES_USER=rt_user
      - POSTGRES_PASSWORD=rt_pass
      - POSTGRES_DB=rt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql://rt_user:rt_pass@dev_db:5432/rt_db
    ports:
      - "8000:8000"
    depends_on:
      - dev_db
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  postgres_data: